import json
import requests
import boto3
import datetime
import random
import os
import re
import logging

# Configure logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

s3 = boto3.client('s3')

# Animal topics for articles
ANIMAL_TOPICS = [
    "The fascinating communication methods of dolphins",
    "How octopuses change color and texture",
    "The incredible migration journey of monarch butterflies",
    "Why sloths are so slow and how they survive",
    "The complex social structure of elephant herds",
    "How hummingbirds hover and fly backwards",
    "The hunting strategies of orcas (killer whales)",
    "Why cats purr and what it really means",
    "The amazing regeneration abilities of axolotls",
    "How bees communicate through the waggle dance",
    "The intelligence and problem-solving skills of crows",
    "Why flamingos stand on one leg",
    "The incredible camouflage of chameleons",
    "How penguins survive in extreme cold",
    "The unique digestive system of cows and ruminants",
    "Why dogs tilt their heads when listening",
    "The symbiotic relationship between clownfish and sea anemones",
    "How bats use echolocation to navigate",
    "The surprising intelligence of pigs",
    "Why and how peacocks display their colorful feathers",
    "The incredible strength of ants",
    "How sharks detect electrical signals",
    "The mysterious sleep patterns of giraffes",
    "Why koalas sleep 18-22 hours a day",
    "The fascinating tool use in wild chimpanzees"
]

AUTHORS = ["Dr. Jane Wildlife", "Alex Rivera", "Sarah Chen", "Michael Thompson", "Emma Rodriguez"]

def generate_article_with_gemini(topic):
    """Generate an article using Google Gemini API"""
    logger.info(f"Starting article generation for topic: {topic}")
    
    api_key = os.environ.get('GEMINI_API_KEY')
    
    if not api_key:
        logger.error("GEMINI_API_KEY environment variable not set")
        raise ValueError("GEMINI_API_KEY environment variable not set")
    
    # Gemini API endpoint - using the correct REST API format
    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
    
    headers = {
        "x-goog-api-key": api_key,
        "Content-Type": "application/json"
    }
    
    prompt = f"""Write an engaging and educational article about: {topic}

The article should:
- Be 300-500 words long
- Include 3-5 fascinating facts about the animal(s)
- Have a clear introduction, main content with interesting facts, and conclusion
- Be written in Markdown format
- Include 3-5 relevant tags (like the animal name, biology, nature, wildlife, etc.)
- Be informative, accurate, and fun to read
- Use an enthusiastic but educational tone

Format your response as valid JSON with these exact fields:
{{
  "title": "A catchy and engaging title for the article",
  "description": "A brief 1-2 sentence description that hooks the reader",
  "tags": ["tag1", "tag2", "tag3"],
  "content": "The full article content in Markdown format with ## headings and paragraphs"
}}

Important: Return ONLY the JSON object, no additional text before or after."""
    
    payload = {
        "contents": [{
            "parts": [{
                "text": prompt
            }]
        }]
    }
    
    logger.info("Sending request to Gemini API...")
    response = requests.post(url, headers=headers, json=payload)
    response.raise_for_status()
    logger.info(f"Gemini API response status: {response.status_code}")
    
    result = response.json()
    
    # Extract the generated text from Gemini's response
    if 'candidates' in result and len(result['candidates']) > 0:
        article_text = result['candidates'][0]['content']['parts'][0]['text']
        logger.info("Successfully extracted article content from Gemini response")
    else:
        logger.error("No content generated by Gemini")
        raise ValueError("No content generated by Gemini")
    
    # Parse JSON from the response (handle markdown code blocks)
    article_text = article_text.strip()
    if article_text.startswith('```json'):
        article_text = article_text[7:]
    if article_text.startswith('```'):
        article_text = article_text[3:]
    if article_text.endswith('```'):
        article_text = article_text[:-3]
    
    # Remove control characters that can break JSON parsing
    article_text = ''.join(char for char in article_text if ord(char) >= 32 or char in '\n\r\t')
    
    return json.loads(article_text.strip())

def lambda_handler(event, context):
    logger.info("Lambda function invoked - Starting article generation process")
    
    bucket = os.environ.get('BUCKET_NAME', 'source-md-bucket')
    logger.info(f"Target S3 bucket: {bucket}")
    
    # Select a random topic and author
    topic = random.choice(ANIMAL_TOPICS)
    author = random.choice(AUTHORS)
    logger.info(f"Selected topic: '{topic}' by author: '{author}'")
    
    try:
        # Generate article using Gemini AI
        article_data = generate_article_with_gemini(topic)
        
        now = datetime.datetime.utcnow()
        timestamp = now.strftime("%Y%m%d_%H%M%S")
        date_str = now.strftime("%Y-%m-%d")
        
        # Create a safe filename from the title
        title = article_data.get('title', 'Untitled Article')
        slug = re.sub(r'[^a-z0-9]+', '-', title.lower())[:50]
        filename = f"{timestamp}-{slug}.md"
        
        # Format tags
        tags = ', '.join(article_data.get('tags', []))
        
        # Calculate estimated reading time (assuming 200 words per minute)
        word_count = len(article_data.get('content', '').split())
        reading_time = max(1, word_count // 200)
        
        # Create the markdown content
        content = f"""---
title: "{title}"
author: "{author}"
date: {date_str}
tags: [{tags}]
reading_time: {reading_time} min
category: animals
generated: true
---

# {title}

**Author:** {author}  
**Published:** {date_str}  
**Tags:** {tags}  
**Reading Time:** {reading_time} min

## Introduction

{article_data.get('description', 'Discover fascinating facts about the animal kingdom.')}

---

{article_data.get('content', '')}

---

*This article was generated using AI technology to share amazing facts about animals and nature.*
"""
        
        # Upload to S3
        logger.info(f"Uploading article to S3: {bucket}/{filename}")
        s3.put_object(
            Bucket=bucket,
            Key=filename,
            Body=content.encode('utf-8'),
            ContentType='text/markdown'
        )
        logger.info(f"Successfully uploaded article to S3")
        
        result = {
            'statusCode': 200,
            'body': json.dumps({
                'file_created': filename,
                'article_title': title,
                'author': author,
                'topic': topic,
                'word_count': word_count
            })
        }
        
        logger.info(f"Article generation completed successfully: {title} ({word_count} words)")
        return result
        
    except Exception as e:
        logger.error(f"Error generating article: {str(e)}", exc_info=True)
        return {
            'statusCode': 500,
            'body': json.dumps({
                'error': str(e),
                'topic': topic
            })
        }